'use strict';
// Support knowledge base. Jev picks the entry that matches a user's question or bug report
// (a judgment, not a generation), and we answer with the fix. Keep answers concrete.
module.exports = [
  { id: 'install-module-not-found', title: "printat: 'Cannot find module /usr/local/agent/connect.js'", match: 'Running printat connect (or any printat command) fails with Cannot find module /usr/local/agent/... MODULE_NOT_FOUND',
    answer: "That was a bug in the `printat` command when it runs through the /usr/local/bin symlink; it is fixed. Update by re-running the installer, which pulls the fix and reinstalls:\n\n    curl -fsSL https://printat.co/install.sh | bash\n\nThen run `printat connect you@email` again. Until then `~/printat/bin/printat connect you@email` also works." },
  { id: 'command-not-found', title: 'printat: command not found', match: 'The shell says printat: command not found after installing',
    answer: "The installer links `printat` into /usr/local/bin, which may not be on your PATH or may not exist. Run it by full path: `~/printat/bin/printat connect you@email`, or re-run the installer: `curl -fsSL https://printat.co/install.sh | bash`." },
  { id: 'xcode-clt', title: 'swiftc not found / Xcode Command Line Tools', match: 'Install fails with swiftc not found, xcrun error, or asks for Xcode Command Line Tools',
    answer: "The driver builds two small Swift helpers. Install the Command Line Tools with `xcode-select --install`, wait for it to finish, then re-run the installer." },
  { id: 'node-version', title: 'Node.js 22+ required', match: 'Installer says Node.js 22+ is required, or node is not installed, or an old Node version',
    answer: "Install a current Node.js from https://nodejs.org (or `brew install node`), then re-run the installer." },
  { id: 'connect-link', title: 'Connect link expired or never arrived', match: 'printat connect timed out, the confirmation email never came, or the link says expired',
    answer: "The link lasts 15 minutes and the command waits about 10 minutes. Check spam for a mail from print@printat.co, then run `printat connect you@email` again and click the newest link. `printat status` confirms when you are connected." },
  { id: 'printer-missing', title: 'Print@ Nearby is not in the Print dialog', match: 'Print@ Nearby does not appear in the printer menu of the Print dialog',
    answer: "Re-run `sudo ~/printat/install.sh` (it re-registers the printer). If it is listed under System Settings › Printers & Scanners but paused, run `cupsenable PrintAt`. Some apps need a restart to refresh the printer list." },
  { id: 'no-research', title: 'Ranked without AI research', match: 'The results say ranked without AI research, or ask to install Claude Code, or only chains show hours and prices',
    answer: "The research step (hours, prices, how a local shop takes files) needs a brain: install Claude Code (Max plan) and it is used automatically, or open the console at http://127.0.0.1:4243/ and add an Anthropic or OpenAI API key under Research. Without one, Print@ still sends to chains, hotel and library printers and kiosks by their known addresses." },
  { id: 'location', title: 'It thinks I am somewhere else', match: 'Wrong location, location services denied, shops from the wrong city',
    answer: "macOS denies Location Services to the command-line helper, so Print@ falls back to your IP, then to the Home address in the console (http://127.0.0.1:4243/). Set Home address there, or set 'Confirm my location first' to Always in the Print dialog options." },
  { id: 'mail-permission', title: 'macOS blocked Print@ from controlling Mail', match: 'Local mode send fails with Mail.app automation blocked, not authorized to send Apple events, or Automation permission',
    answer: "Local-only mode sends through Mail.app and macOS asks once for permission. Allow it under System Settings › Privacy & Security › Automation (the Print@ agent, Mail), then print again. Or connect to the cloud (`printat connect`) and skip local sending entirely." },
  { id: 'job-stuck', title: 'The job sits in the queue or the window never appears', match: 'Print job stuck, queue paused, nothing happens after printing, status window did not open',
    answer: "Restart the agent: `launchctl kickstart -k gui/$(id -u)/io.printat.agent`, then `cupsenable PrintAt`. Logs are in ~/Library/Logs/PrintAt/. If it keeps happening, send us the last lines of agent.log with the bug report." },
  { id: 'shop-reply', title: 'How do I hear back from the shop?', match: 'Waiting for the shop to reply, price confirmation, pickup code, release code',
    answer: "Orders go out from print@printat.co with a reply address that routes straight back to you, so the shop's reply lands in your inbox. Chains and kiosks send a release code by email instead. Check spam once; the receipt on your Mac also has the shop's phone." },
  { id: 'update', title: 'How do I update?', match: 'Update, new version, latest, upgrade the driver',
    answer: "The driver checks daily and shows an Update available banner in the console at http://127.0.0.1:4243/ with an Update now button; one click pulls the new version and restarts the agent. From Terminal, `printat update` does the same (and re-running the installer too)." },
  { id: 'uninstall', title: 'How do I uninstall?', match: 'Remove Print@, uninstall, delete the printer',
    answer: "`~/printat/uninstall.sh` removes the printer, backend and agent. Delete ~/printat afterwards if you want the code gone too." },
  { id: 'cost', title: 'What does it cost?', match: 'Price, cost, free, subscription, billing',
    answer: "The driver is free and open source (MIT). The Print@ cloud is free at launch. If you bring your own API key for research you pay your provider directly; with Claude Code there is nothing extra." },
  { id: 'platforms', title: 'Windows or Linux?', match: 'Windows, Linux, iPhone, Android, other platforms',
    answer: "macOS only today. Windows and Linux ports are scaffolded in the repo and help is wanted: https://github.com/AnthonyDavidAdams/print-at. On a phone, the web portal at https://printat.co/app sends a job to a Print@ Network shop without any install." },
];
